### ISSUE TITLE
code/model availability

### ISSUE THREAD

**Issue by bgriffen** [Unco3892/SRED_2022#1]
Would this code be made available in the spirit of reproducibility? Apologies if I've missed it elsewhere.

**Comment by Unco3892** [comment]
Hello. Thanks for raising this point. There was no plan to share the code on GitHub (that's why you haven't found it), but I would happily share the code (written in R) for the regression part. Particularly the neural network cross-validation depending on what you exactly need (also other ML techniques like XGB and others, but they may require more organization). For reproducibility, I have all the logs of the cross-validated runs, and I have just shared them and added instructions for running them in the [README file](https://github.com/Unco3892/SRED_2022/blob/main/README.md) (see 6b55f0d9a0b7630d46e1e8fc047c76344c4a5a26 for the logs). If you needed the code, I can additionally share the requirements for the conda environment.

The code for the other parts is quite exhaustive, but I will "probably" deploy an application soon based on the paper so those interested can play around with it. If you're interested in a particular part of the code, let me know, and I'll share it.
